version: 0.0
os: linux # Ubuntu니까 linux로 설정.
files:
  - source: /
    destination: /home/ubuntu/cuniverse # EC2 인스턴스 안에 프로젝트를 저장할 경로.
    overwrite: yes
permissions: # EC2 인스턴스에 프로젝트를 저장하기 위한 권한 설정.
  - object: /home/ubuntu/cuniverse # EC2 인스턴스 안에 프로젝트를 저장할 경로.
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall: # AfterInstall 즉, 배포 완료 후 실행할 동작 설정.
    - location: deploy.sh # deploy.sh를 실행.
      timeout: 60 # 제한 시간 60초 으로 설정. 60초가 넘어가면 실패함.
      runas: root # run as root 즉, root 권한으로 실행.
