import Header from "@/components/common/Header";
import "@/css/globals.scss";
import type { Metadata } from "next";
import ReactQueryProvider from "@/utils/provider";
import Background from "@/components/common/Background";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <Header />
          <Background />
          <div id="main-contents-container">{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
